### ISSUE TITLE
Issue with connectivity to OPC UA server.

### ISSUE THREAD

**Issue by eamonn145** [syndrome5/KpOpcUA#2]
Hi,

Ive installed the OPC UA driver through the file you supply and by building it through the source code, however the same issue is still present. I can't seem to connect to the server we have set up with the tags. I was wondering if you could possibly see what the problem is or whether we have missed out on something crucial that allows the driver to run as it should do. Please find attached some photos of the problems we are finding and what has been created with the source code.

The DLL's created with the source code
![dll s created with visual studio for opc ua driver](https://user-images.githubusercontent.com/39824246/41040098-5aefbc44-6993-11e8-8ba7-a7f6e2a2c58e.PNG)

the log in the Rapid Scada communicator app.
![log for opc ua driver](https://user-images.githubusercontent.com/39824246/41040100-5b108578-6993-11e8-8c7e-2f06e24b9aef.png)

the properties page where you connect to your server.
![properties page for opc ua driver](https://user-images.githubusercontent.com/39824246/41040101-5b28c0d4-6993-11e8-8430-947240f66aab.png)

note the address is this image is not our one, we have tried changing it numerous times in the config file but it keeps returning with this. Even when we edit it in this window it doesnt allow connectivity to the server address we have set up.

thanks for any help in advance.

**Comment by syndrome5** [comment]
Hello,
As it's written in the readme, the window on the last screen is not working yet.
If you tried to connect from this window, the error is normal.
The DLL only works in background, and you have to make your all configurations by hand without RapidScada GUI. Please double-check all of your configurations files, installation procedure, rights, OPC UA Server open and correctly configured/accessible by the client.
You can have more details of the problem insinde SCADA/ScadaComm/Log/lineXYYY.log (depends on your line)
